export type SeedRestaurant = {
  slug: string;
  name: string;
  city: string;
  neighborhood: string;
  cuisine: string;
  priceRange: number;
  rating: number;
  reviewCount: number;
  description: string;
  address: string;
  phone: string;
  opensAt: string;
  closesAt: string;
  accent: string;
  emoji: string;
  popularDishes: string[];
};

export const CITIES = [
  "Dar es Salaam",
  "Arusha",
  "Zanzibar",
  "Mwanza",
  "Dodoma",
  "Moshi",
  "Mbeya",
  "Tanga",
] as const;

export const CUISINES = [
  "Vyakula vya Kiswahili",
  "Nyama Choma",
  "Vyakula vya Baharini",
  "Vyakula vya Kihindi",
  "Vyakula vya Kiitaliano",
  "Vyakula vya Kichina",
  "Kahawa na Vitafunio",
  "Fusion ya Kisasa",
] as const;

export const SEED_RESTAURANTS: SeedRestaurant[] = [
  {
    slug: "baharini-grill-msasani",
    name: "Baharini Grill",
    city: "Dar es Salaam",
    neighborhood: "Msasani",
    cuisine: "Vyakula vya Baharini",
    priceRange: 3,
    rating: 4.7,
    reviewCount: 482,
    description:
      "Mkahawa wa kifahari kando ya bahari unaotoa samaki wabichi, kamba na pweza vilivyoandaliwa kwa mtindo wa pwani. Machweo mazuri ya jua ni zawadi ya ziada.",
    address: "Barabara ya Msasani, Peninsula, Dar es Salaam",
    phone: "+255 22 260 1234",
    opensAt: "11:00",
    closesAt: "23:00",
    accent: "from-teal-500 to-cyan-600",
    emoji: "🦐",
    popularDishes: ["Samaki wa kupaka", "Pweza wa kuchoma", "Wali wa kamba"],
  },
  {
    slug: "nyama-choma-palace-kinondoni",
    name: "Nyama Choma Palace",
    city: "Dar es Salaam",
    neighborhood: "Kinondoni",
    cuisine: "Nyama Choma",
    priceRange: 2,
    rating: 4.6,
    reviewCount: 915,
    description:
      "Chapisho maarufu la nyama choma yenye harufu nzuri, ugali wa moto na kachumbari mbichi. Mahali pazuri pa kukutana na marafiki jioni ya Ijumaa.",
    address: "Mtaa wa Ali Hassan Mwinyi, Kinondoni, Dar es Salaam",
    phone: "+255 22 277 4455",
    opensAt: "12:00",
    closesAt: "00:00",
    accent: "from-orange-500 to-red-600",
    emoji: "🍖",
    popularDishes: ["Nyama choma ya mbuzi", "Ugali na mchuzi", "Kachumbari"],
  },
  {
    slug: "mezani-ya-mama-upanga",
    name: "Mezani ya Mama",
    city: "Dar es Salaam",
    neighborhood: "Upanga",
    cuisine: "Vyakula vya Kiswahili",
    priceRange: 1,
    rating: 4.8,
    reviewCount: 671,
    description:
      "Chakula cha nyumbani chenye ladha ya asili — wali wa nazi, mchuzi wa samaki na mboga za majani. Kama vile bibi angepika mwenyewe.",
    address: "Mtaa wa Upanga Magharibi, Dar es Salaam",
    phone: "+255 76 512 3344",
    opensAt: "07:00",
    closesAt: "21:00",
    accent: "from-amber-500 to-yellow-600",
    emoji: "🍛",
    popularDishes: ["Wali wa nazi na samaki", "Mchicha na karanga", "Maharage ya nazi"],
  },
  {
    slug: "spice-route-oyster-bay",
    name: "Spice Route",
    city: "Dar es Salaam",
    neighborhood: "Oyster Bay",
    cuisine: "Vyakula vya Kihindi",
    priceRange: 3,
    rating: 4.5,
    reviewCount: 356,
    description:
      "Ladha za viungo kutoka Zanzibar na Bara Hindi zinazokutana kwenye sahani moja. Curry za moto na mikate ya naan iliyookwa kwa jiko la tandoor.",
    address: "Barabara ya Toure, Oyster Bay, Dar es Salaam",
    phone: "+255 22 266 7788",
    opensAt: "12:00",
    closesAt: "22:30",
    accent: "from-rose-500 to-orange-600",
    emoji: "🍛",
    popularDishes: ["Butter chicken", "Naan ya sarafina", "Biryani ya kondoo"],
  },
  {
    slug: "dolce-vita-masaki",
    name: "Dolce Vita",
    city: "Dar es Salaam",
    neighborhood: "Masaki",
    cuisine: "Vyakula vya Kiitaliano",
    priceRange: 3,
    rating: 4.4,
    reviewCount: 289,
    description:
      "Pizza ya jiko la kuni, pasta safi na divai kutoka Ulaya, kwenye ukumbi wenye mandhari nzuri ya bustani huko Masaki.",
    address: "Mtaa wa Chole, Masaki, Dar es Salaam",
    phone: "+255 22 260 9911",
    opensAt: "11:30",
    closesAt: "23:00",
    accent: "from-green-600 to-emerald-700",
    emoji: "🍕",
    popularDishes: ["Pizza Margherita", "Pasta ya kamba", "Tiramisu"],
  },
  {
    slug: "golden-dragon-city-centre",
    name: "Golden Dragon",
    city: "Dar es Salaam",
    neighborhood: "Kati ya Jiji",
    cuisine: "Vyakula vya Kichina",
    priceRange: 2,
    rating: 4.3,
    reviewCount: 204,
    description:
      "Chakula cha Kichina cha jadi — dim sum, noodles na kuku wa tamu-chungu, kilichoandaliwa na wapishi wenye uzoefu wa miaka mingi.",
    address: "Mtaa wa Samora, Kati ya Jiji, Dar es Salaam",
    phone: "+255 22 213 5566",
    opensAt: "11:00",
    closesAt: "22:00",
    accent: "from-red-600 to-yellow-500",
    emoji: "🥟",
    popularDishes: ["Kuku wa tamu-chungu", "Noodles za mboga", "Dumplings"],
  },
  {
    slug: "serengeti-terrace-arusha",
    name: "Serengeti Terrace",
    city: "Arusha",
    neighborhood: "Kati ya Mji",
    cuisine: "Fusion ya Kisasa",
    priceRange: 3,
    rating: 4.7,
    reviewCount: 398,
    description:
      "Mkahawa wa kisasa unaochanganya ladha za asili na mtindo wa kimataifa, ukiwa na mandhari nzuri ya Mlima Meru mbele yako.",
    address: "Barabara ya Sokoine, Arusha",
    phone: "+255 27 254 7788",
    opensAt: "10:00",
    closesAt: "22:30",
    accent: "from-emerald-600 to-teal-700",
    emoji: "🌿",
    popularDishes: ["Steak ya nyati", "Supu ya karoti na tangawizi", "Samaki wa mtoni"],
  },
  {
    slug: "kilimanjaro-coffee-house-arusha",
    name: "Kilimanjaro Coffee House",
    city: "Arusha",
    neighborhood: "Njiro",
    cuisine: "Kahawa na Vitafunio",
    priceRange: 1,
    rating: 4.6,
    reviewCount: 512,
    description:
      "Kahawa halisi ya Kitanzania iliyookwa hapa hapa, pamoja na keki na vitafunio vya asubuhi. Mahali pazuri pa mikutano ya kazi.",
    address: "Barabara ya Njiro, Arusha",
    phone: "+255 27 250 3321",
    opensAt: "06:30",
    closesAt: "19:00",
    accent: "from-amber-700 to-orange-800",
    emoji: "☕",
    popularDishes: ["Kahawa ya Kilimanjaro", "Chapati na maharage", "Keki ya ndizi"],
  },
  {
    slug: "meru-choma-house-arusha",
    name: "Meru Choma House",
    city: "Arusha",
    neighborhood: "Sekei",
    cuisine: "Nyama Choma",
    priceRange: 2,
    rating: 4.5,
    reviewCount: 340,
    description:
      "Nyama choma ya hali ya juu ikiwa na muziki wa bongo fleva na ukumbi mkubwa wa nje kwa ajili ya familia na vikundi.",
    address: "Barabara ya Sekei, Arusha",
    phone: "+255 27 250 9987",
    opensAt: "12:00",
    closesAt: "23:30",
    accent: "from-orange-600 to-amber-700",
    emoji: "🍖",
    popularDishes: ["Mbavu za ng'ombe", "Kuku wa kuchoma", "Ndizi za kuchoma"],
  },
  {
    slug: "mji-mkongwe-seafood-zanzibar",
    name: "Mji Mkongwe Seafood",
    city: "Zanzibar",
    neighborhood: "Mji Mkongwe",
    cuisine: "Vyakula vya Baharini",
    priceRange: 3,
    rating: 4.9,
    reviewCount: 764,
    description:
      "Ndani ya kuta za kihistoria za Mji Mkongwe, mkahawa huu hutoa dagaa safi wa Zanzibar wenye ladha ya viungo vya kisiwani.",
    address: "Mji Mkongwe, Unguja, Zanzibar",
    phone: "+255 24 223 4567",
    opensAt: "11:00",
    closesAt: "23:00",
    accent: "from-cyan-600 to-blue-700",
    emoji: "🦞",
    popularDishes: ["Kamba wa nazi", "Pweza wa viungo", "Wali wa kuku wa Kizanzibari"],
  },
  {
    slug: "spice-island-kitchen-zanzibar",
    name: "Spice Island Kitchen",
    city: "Zanzibar",
    neighborhood: "Stone Town",
    cuisine: "Vyakula vya Kiswahili",
    priceRange: 2,
    rating: 4.6,
    reviewCount: 421,
    description:
      "Sahani za jadi za Zanzibar zilizoandaliwa kwa viungo vinavyolimwa kisiwani humo — karafuu, iliki na mdalasini.",
    address: "Forodhani, Stone Town, Zanzibar",
    phone: "+255 24 223 8890",
    opensAt: "10:00",
    closesAt: "22:00",
    accent: "from-fuchsia-600 to-purple-700",
    emoji: "🌶️",
    popularDishes: ["Biryani ya Kizanzibari", "Urojo", "Mtori wa ndizi"],
  },
  {
    slug: "sunset-terrace-nungwi",
    name: "Sunset Terrace",
    city: "Zanzibar",
    neighborhood: "Nungwi",
    cuisine: "Fusion ya Kisasa",
    priceRange: 3,
    rating: 4.8,
    reviewCount: 588,
    description:
      "Ukumbi wa nje kando ya bahari ya Nungwi, bora kwa chakula cha jioni chenye mapenzi wakati jua linapotua baharini.",
    address: "Ufukwe wa Nungwi, Zanzibar",
    phone: "+255 24 224 1122",
    opensAt: "12:00",
    closesAt: "23:30",
    accent: "from-pink-500 to-rose-600",
    emoji: "🌅",
    popularDishes: ["Tuna ya kuchoma", "Saladi ya matunda ya kitropiki", "Cocktail ya madafu"],
  },
  {
    slug: "victoria-view-mwanza",
    name: "Victoria View",
    city: "Mwanza",
    neighborhood: "Isamilo",
    cuisine: "Vyakula vya Baharini",
    priceRange: 2,
    rating: 4.5,
    reviewCount: 276,
    description:
      "Mandhari nzuri ya Ziwa Victoria na sangara wa ziwa aliyeandaliwa kwa mitindo mbalimbali — wa kuchoma, kukaanga au kupikwa kwa mchuzi.",
    address: "Barabara ya Kenyatta, Isamilo, Mwanza",
    phone: "+255 28 250 6677",
    opensAt: "11:00",
    closesAt: "22:00",
    accent: "from-blue-600 to-indigo-700",
    emoji: "🐟",
    popularDishes: ["Sangara wa kuchoma", "Supu ya samaki", "Wali wa samaki"],
  },
  {
    slug: "rock-city-grill-mwanza",
    name: "Rock City Grill",
    city: "Mwanza",
    neighborhood: "Kati ya Mji",
    cuisine: "Nyama Choma",
    priceRange: 2,
    rating: 4.4,
    reviewCount: 198,
    description:
      "Jina limetokana na miamba maarufu ya Mwanza — mkahawa huu una nyama choma nzuri na muziki wa moja kwa moja wikendi.",
    address: "Barabara ya Station, Mwanza",
    phone: "+255 28 250 1188",
    opensAt: "12:00",
    closesAt: "00:00",
    accent: "from-stone-600 to-neutral-800",
    emoji: "🍢",
    popularDishes: ["Mishikaki", "Nyama choma ya ng'ombe", "Chips mayai"],
  },
  {
    slug: "capital-garden-dodoma",
    name: "Capital Garden",
    city: "Dodoma",
    neighborhood: "Kati ya Mji",
    cuisine: "Vyakula vya Kiswahili",
    priceRange: 1,
    rating: 4.3,
    reviewCount: 152,
    description:
      "Bustani tulivu katikati ya jiji kuu la Dodoma, ikitoa vyakula vya asili pamoja na divai za mzabibu wa Dodoma.",
    address: "Barabara ya Uhuru, Dodoma",
    phone: "+255 26 232 4455",
    opensAt: "08:00",
    closesAt: "21:30",
    accent: "from-lime-600 to-green-700",
    emoji: "🍇",
    popularDishes: ["Kuku wa kienyeji", "Wali wa maharage", "Divai ya Dodoma"],
  },
  {
    slug: "uhuru-bites-dodoma",
    name: "Uhuru Bites",
    city: "Dodoma",
    neighborhood: "Area C",
    cuisine: "Kahawa na Vitafunio",
    priceRange: 1,
    rating: 4.2,
    reviewCount: 133,
    description:
      "Mkahawa mdogo wa kifamilia unaotoa chai ya tangawizi, sambusa na maandazi mapya kila asubuhi.",
    address: "Area C, Dodoma",
    phone: "+255 26 232 9900",
    opensAt: "06:00",
    closesAt: "20:00",
    accent: "from-yellow-600 to-amber-700",
    emoji: "🥟",
    popularDishes: ["Sambusa za nyama", "Chai ya tangawizi", "Maandazi"],
  },
  {
    slug: "fahari-lodge-dodoma",
    name: "Fahari Lodge",
    city: "Dodoma",
    neighborhood: "Nyerere Square",
    cuisine: "Fusion ya Kisasa",
    priceRange: 3,
    rating: 4.6,
    reviewCount: 187,
    description:
      "Mkahawa wa kifahari ndani ya Fahari Lodge, ukitoa chakula cha kisasa kilichochanganywa na ladha za asili, pamoja na ukumbi mtulivu wa bustani unaofaa kwa wageni wa kazi na familia.",
    address: "Barabara ya Nyerere Square, Dodoma",
    phone: "+255 713 597 956",
    opensAt: "07:00",
    closesAt: "22:30",
    accent: "from-violet-600 to-indigo-700",
    emoji: "🏨",
    popularDishes: ["Nyama ya ng'ombe ya kupaka", "Saladi ya kuku", "Wali wa kuku wa kienyeji"],
  },
  {
    slug: "kibo-view-moshi",
    name: "Kibo View",
    city: "Moshi",
    neighborhood: "Kati ya Mji",
    cuisine: "Fusion ya Kisasa",
    priceRange: 2,
    rating: 4.7,
    reviewCount: 245,
    description:
      "Kwa macho ya Mlima Kilimanjaro, mkahawa huu unatoa vyakula vya kisasa vilivyochanganywa na ladha za kienyeji za Chagga.",
    address: "Barabara ya Kilimanjaro, Moshi",
    phone: "+255 27 275 2211",
    opensAt: "09:00",
    closesAt: "22:00",
    accent: "from-sky-600 to-blue-800",
    emoji: "🏔️",
    popularDishes: ["Mtori wa ndizi na nyama", "Trout ya kupaka", "Kahawa ya Chagga"],
  },
  {
    slug: "uwanda-wa-kahawa-mbeya",
    name: "Uwanda wa Kahawa",
    city: "Mbeya",
    neighborhood: "Loleza",
    cuisine: "Kahawa na Vitafunio",
    priceRange: 1,
    rating: 4.6,
    reviewCount: 168,
    description:
      "Kahawa halisi ya nyanda za juu za Mbeya, iliyookwa hapa hapa kutoka mashamba ya karibu ya Mbozi na Rungwe, pamoja na keki za nyumbani.",
    address: "Barabara ya Loleza, Mbeya",
    phone: "+255 25 250 4433",
    opensAt: "06:30",
    closesAt: "19:30",
    accent: "from-amber-800 to-stone-800",
    emoji: "☕",
    popularDishes: ["Kahawa ya Mbozi", "Chapati na maharage", "Keki ya karoti"],
  },
  {
    slug: "loleza-grill-mbeya",
    name: "Loleza Grill",
    city: "Mbeya",
    neighborhood: "Kati ya Mji",
    cuisine: "Nyama Choma",
    priceRange: 2,
    rating: 4.5,
    reviewCount: 221,
    description:
      "Mkahawa wa nyama choma wenye mandhari ya Mlima Loleza, maarufu kwa nyama ya ng'ombe wa nyanda za juu na supu ya moto ya jioni baridi.",
    address: "Barabara ya Uzunguni, Mbeya",
    phone: "+255 25 250 7788",
    opensAt: "12:00",
    closesAt: "23:00",
    accent: "from-orange-700 to-red-800",
    emoji: "🍖",
    popularDishes: ["Nyama choma ya ng'ombe", "Supu ya mifupa", "Ugali na mboga za majani"],
  },
  {
    slug: "amboni-seafood-terrace-tanga",
    name: "Amboni Seafood Terrace",
    city: "Tanga",
    neighborhood: "Ras Kazone",
    cuisine: "Vyakula vya Baharini",
    priceRange: 3,
    rating: 4.7,
    reviewCount: 312,
    description:
      "Ukumbi wa nje kando ya Bahari ya Hindi huko Ras Kazone, ukitoa dagaa wabichi wa Tanga na mandhari nzuri ya pwani.",
    address: "Ras Kazone, Tanga",
    phone: "+255 27 264 5566",
    opensAt: "11:00",
    closesAt: "22:30",
    accent: "from-sky-600 to-teal-700",
    emoji: "🦀",
    popularDishes: ["Kaa wa kupaka", "Samaki wa kuchoma", "Wali wa kuku wa pwani"],
  },
  {
    slug: "sisal-route-kitchen-tanga",
    name: "Sisal Route Kitchen",
    city: "Tanga",
    neighborhood: "Kati ya Mji",
    cuisine: "Vyakula vya Kiswahili",
    priceRange: 1,
    rating: 4.4,
    reviewCount: 176,
    description:
      "Jina limetokana na historia ya mashamba ya mkonge ya Tanga — mkahawa huu unatoa vyakula vya nyumbani vya pwani kwa bei nafuu.",
    address: "Mtaa wa Independence, Tanga",
    phone: "+255 27 264 2211",
    opensAt: "07:00",
    closesAt: "21:00",
    accent: "from-lime-700 to-green-800",
    emoji: "🥥",
    popularDishes: ["Wali wa nazi na kamba", "Mchuzi wa maharage", "Vitumbua"],
  },
];
